sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - TEST_COVERAGE=true
    - php: 7
      env:
        - CS_CHECK=true
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls:^1.0 ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update michaelmoussa/php-coverage-checker:^1.1.0 ; fi

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer check-coverage ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: true
